### ISSUE TITLE
ReferenceError: heartbeatErrors is not defined

### ISSUE THREAD

**Issue by Controlix** [squarebracket/karma-selenium-grid-launcher#1]
When a browser fails to start for some reason, I get this error:
`02 07 2019 09:32:31.624:ERROR [karma-server]: ReferenceError: heartbeatErrors is not defined
    at C:\workspace\ing-web\node_modules\karma-selenium-grid-launcher\index.js:149:9
    at processTicksAndRejections (internal/process/task_queues.js:89:5)`

I inspected the code `index.js` and indeed the variable is defined elsewhere.

**Comment by squarebracket** [comment]
I've been refactoring / cleaning up / improving the code to, among other things, improve error handling during startup. I'll release it in a couple days after I finish up another couple things. In the mean time, you can point your package.json's dependency to `github:squarebracket/karma-selenium-grid-launcher#tmp/refactor` if you wish, though I may not have updated the documentation since it's a WIP.

**Comment by squarebracket** [comment]
Apologies for taking so long. 0.3.0 has just been published to npm. It contains several improvements to stability.

Please let me know if you have any issues in the future.
